on: 
  push:
    branches: 
      - master2
  





jobs: 
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'test print before'
        run: ls

      - uses: actions/checkout@v3 

      - name: 'test print after'
        run: ls 
      
