on: 
  push:
    branches: 
      - master2
  





jobs: 
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3 
      
      - name: "login"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.TOCKEN}}
      
      - name: "build img"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dragon .

      - name: "push"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dragon  

      
